platform :ios, '9.0'

target 'PPnoStoryboards' do
  
  use_frameworks!

  # Pods for PPnoStoryboards

	pod "Macaw", "0.9.5"
	pod 'SVProgressHUD'

  target 'PPnoStoryboardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PPnoStoryboardsUITests' do
    # Pods for testing
  end

end
